### ISSUE TITLE
Add a way to generate a markdown changelog using Koumu's convention

### ISSUE THREAD

**Issue by noomly** [noomly/koumu#15]
Either by integrating with another tool and document it or by writing such a tool from scratch.

**Comment by noomly** [comment]
It is definitely possible to generate such changlog using [git-cliff](https://github.com/orhun/git-cliff). The configuration for Koumu would be like this for example:

```toml
[changelog]
header = """
# Koumu's Changelog\n
"""
trim = true

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = false
# process each line of a commit as an individual commit
split_commits = false
commit_parsers = [
    { message = "^:sparkles:", group = "Features"},
    { message = "^:bug:", group = "Bug Fixes"},
    { message = "^:books:", group = "Documentation"},
    { message = "^:racehorse:", group = "Performance"},
    # { message = "^:recycle:", group = "Refactor"},
    # { message = "^:lipstick:", group = "Styling"},
    # { message = "^:white_check_mark:", group = "Testing"},
]
# filter out the commits that are not matched by commit parsers
filter_commits = true
# glob pattern for matching git tags
tag_pattern = "v[0-9]*"
# sort the tags chronologically
date_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
```

Maybe Koumu could offer a way to auto-generate the `[git]` section of cliff's configuration? Anyway a first step would be to document its usage somewhere (wiki page, readme, docs folder, ...).
